language: php
php:
  - "5.4"
before_script:
  - echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - npm install uglify-js
  - git clone https://github.com/nsams/libsass.git; cd libsass; make; git clone https://github.com/hcatlin/sassc.git ; cd sassc; SASS_LIBSASS_PATH=.. make; cd ../..
  - printf "\n" | pecl install imagick
  - echo "short_open_tag = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "[production]" > tests/config.local.ini
  - echo "server.domain = localhost:8080" >> tests/config.local.ini
  - echo 'server.baseUrl = ""' >> tests/config.local.ini
  - echo "server.uglifyjs = `pwd`/node_modules/.bin/uglifyjs" >> tests/config.local.ini
  - echo "server.sassc = `pwd`/libsass/sassc/bin/sassc" >> tests/config.local.ini
  - chmod a+w cache/*
  - composer self-update
  - composer install
  - php -S localhost:8080 bootstrap.php &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done
services:
  - memcached
script: "./vendor/bin/phpunit"
notificaitons:
  irc: "irc.freenode.org#kwf"

# caching doesn't work for free travis atm, but one day it probably will
cache:
  directories:
    - /tmp/kwf-uglifyjs
    - $HOME/.composer/cache

